### ISSUE TITLE
Docker build on linux/arm* fails

### ISSUE THREAD

**Issue by brotandgames** [brotandgames/ciao#129]
**Describe the bug**

Docker build on linux/arm* fails

```sh
#29 [linux/arm64 8/9] COPY . ./
#29 DONE 0.3s

#30 [linux/arm64 9/9] RUN set -x     && apk add --no-cache xz-libs     && SECRET_KEY_BASE=foo bundle exec rake assets:precompile     && rm -rf         /tmp/*         app/assets         lib/assets         node_modules         spec         tmp/cache         vendor/assets
#30 0.097 + apk add --no-cache xz-libs
#30 0.154 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
#30 0.712 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
#30 1.710 (1/1) Installing xz-libs (5.2.5-r0)
#30 1.762 OK: 69 MiB in 45 packages
#30 1.875 + SECRET_KEY_BASE=foo bundle exec rake assets:precompile
#30 18.72 rake aborted!
#30 18.72 LoadError: cannot load such file -- nokogiri/nokogiri
#30 18.72 /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
#30 18.72 /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
```

Build for arm is currently disabled: [Build only for linux/amd64 because linux/arm* currently broken](https://github.com/brotandgames/ciao/commit/ea8cd9a5328eddaa467a7848ade08a68d313fcab)

**To Reproduce**

See GitHub Action run https://github.com/brotandgames/ciao/runs/5795452795?check_suite_focus=true

**Expected behavior**

Docker build on linux/arm* succeeds

**Comment by brotandgames** [comment]
Fixed in version 1.7.0 https://github.com/brotandgames/ciao/commit/cda0afd66a4cae62bb01f5aa3395306905969c47.
